homepage: "https://github.com/google/gemini-cli"
language: javascript
primary_contact: "oss-fuzz-team@google.com"
auto_ccs:
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/google/gemini-cli"